INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 611369, 'Honoria');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 120525, 'Vasilis');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 39836, 'Isidor');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 75446, 'Fidelity');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 240753, 'Mata');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 1776, 'Brocky');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 64271, 'Paxon');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 924722, 'Eolande');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 561442, 'Berton');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 171573, 'Stephanus');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 709166, 'Amitie');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 189760, 'Reagan');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 404010, 'Karrah');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 981804, 'Drud');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 149659, 'Murry');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 772041, 'Bennie');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 262260, 'Davidde');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 382415, 'Nana');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 280192, 'Otes');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 460720, 'Mattie');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 41211, 'Zaccaria');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 645182, 'Berny');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 297963, 'Matilda');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 421839, 'Creigh');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 314807, 'Marina');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 10049, 'Bondie');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 722005, 'Wilma');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 782449, 'Rikki');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 559941, 'Garald');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 500101, 'Yoko');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 26827, 'Auberon');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 735116, 'Elbert');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 412542, 'Daniela');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 614037, 'Ado');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 96406, 'Stanislas');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 990702, 'Willie');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 43393, 'Agosto');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 350488, 'Beatrice');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 130637, 'Ami');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 953507, 'Arlina');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 631101, 'Shani');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 696390, 'Noak');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 160207, 'Giffie');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 804448, 'Meridel');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 989566, 'Marrilee');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 882003, 'Ericha');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 249482, 'Burlie');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 377756, 'Guthry');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 38346, 'Goldie');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 521977, 'Bucky');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 912414, 'Loella');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 233171, 'Merlina');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 439075, 'Neville');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 62400, 'Giselbert');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 358172, 'Lorette');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 318457, 'Shauna');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 554904, 'Correna');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 305594, 'Marci');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 639461, 'Jacynth');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 194940, 'Griffie');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 639489, 'Franny');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 469628, 'Hagan');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 795982, 'Rhea');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 320380, 'Marcella');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 666642, 'Brigitte');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 195861, 'Christian');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 589053, 'Verina');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 338204, 'Owen');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 383920, 'Henrieta');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 289460, 'Emili');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 823938, 'Dana');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 746066, 'Joly');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 144647, 'Shalna');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 456611, 'Danica');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 127993, 'Swen');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 721844, 'Quint');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 274496, 'Jerome');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 821705, 'Terri');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 740858, 'Maxwell');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 738892, 'Sibella');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 896165, 'Bev');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 993102, 'Morgun');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 897442, 'Eugenia');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 828170, 'Blaire');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 834468, 'Lita');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 952537, 'Shina');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 254081, 'Oralee');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 518182, 'Lita');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 659945, 'Rodie');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 754258, 'Letta');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 603133, 'Malina');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 382044, 'Merrel');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 147440, 'Kalinda');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 313462, 'Darb');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 383138, 'Bradley');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 87163, 'Giles');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 38968, 'Brittan');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 627078, 'Esteban');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 429196, 'Osbert');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 723261, 'Phaidra');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 512679, 'Boris');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 871848, 'Jacquenette');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 958040, 'Dickie');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 425602, 'Jenine');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 172059, 'Robyn');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 618235, 'Che');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 116159, 'Loutitia');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 918569, 'Inigo');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 419989, 'Bernardina');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 705653, 'Paola');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 107750, 'Rad');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 693968, 'Claretta');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 568001, 'Haskell');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 923056, 'Jemima');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 307181, 'Andeee');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 840612, 'Loreen');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 703726, 'Aridatha');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 489790, 'Andrey');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 813716, 'Brena');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 819236, 'Jedediah');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 71607, 'Townie');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 789400, 'Ruttger');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 589322, 'Denver');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 322769, 'Jaquelyn');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 591585, 'Ulla');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 458297, 'Brady');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 405884, 'Farlay');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 373020, 'Alisun');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 433561, 'Gavrielle');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 826338, 'Henryetta');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 397718, 'Ludvig');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 816269, 'Chiarra');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 500841, 'Dodie');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 413642, 'Elizabeth');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 854117, 'Cassi');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 445229, 'Chicky');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 170244, 'Nick');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 879319, 'Adelbert');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 594467, 'Mattie');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 176697, 'Gilberte');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 645516, 'Broddy');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 395634, 'Terry');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 31582, 'Jase');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 131240, 'Guy');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 252880, 'Sibella');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 13170, 'Ted');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 126180, 'Velma');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 171235, 'Papagena');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 156852, 'Thoma');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 518700, 'Alys');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 87325, 'Horten');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 467301, 'Jervis');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 811944, 'Georgie');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 360382, 'Stewart');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 952386, 'Marin');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 294975, 'Elihu');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 597893, 'Elmo');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 371078, 'Liza');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 477709, 'Barris');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 785758, 'Ailee');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 73311, 'Tiffanie');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 986779, 'Beatrice');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 65853, 'Oswald');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 254584, 'Cthrine');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 609732, 'Joey');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 171634, 'Fleming');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 298838, 'Yoshiko');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 355968, 'Melisenda');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 843798, 'Tammie');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 687555, 'Clotilda');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 651763, 'Zorana');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 744873, 'Cosimo');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 209068, 'Nicolle');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 845162, 'Margette');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 546320, 'Chandal');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 128328, 'Kaitlynn');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 943055, 'Christy');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 485436, 'Ossie');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 743047, 'Drona');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 44221, 'Cati');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 848028, 'Celinka');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 58627, 'Raven');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 985026, 'Torrence');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 758926, 'Erhart');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 137837, 'Flory');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 914146, 'Gayelord');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 941054, 'Valle');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 271546, 'Maribeth');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 929131, 'Marcela');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 574640, 'Constancy');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 453036, 'Betti');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 356018, 'Goldy');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 46253, 'Jonathan');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 607653, 'Vonnie');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 68217, 'Sheridan');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 768850, 'Roxanne');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 489900, 'Tresa');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 282405, 'Andres');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 139475, 'Harcourt');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 125377, 'Esme');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 453321, 'Bren');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 55967, 'Orion');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 986135, 'Ursulina');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 778985, 'Vasily');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 229198, 'Curran');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 79686, 'Saunders');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 794568, 'Kore');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 931020, 'Cortie');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 8671, 'Brigg');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 817387, 'Antonina');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 864252, 'Marla');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 769257, 'Hesther');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 339327, 'Nelle');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 861551, 'Mendel');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 977220, 'Randa');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 98082, 'Hal');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 617589, 'Dun');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 551855, 'Aile');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 150194, 'Laural');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 837161, 'Crissie');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 909350, 'Omero');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 936586, 'Laraine');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 208698, 'Angel');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 720477, 'Donn');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 552839, 'Natalya');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 374756, 'Cammi');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 973962, 'Minna');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 137818, 'Lauren');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 504277, 'Sollie');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 922196, 'Carmelita');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 418868, 'Marthe');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 810675, 'Spenser');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 471543, 'Linnet');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 224964, 'Dode');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 940764, 'Chance');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 472874, 'Terri');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 91303, 'Salome');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 634980, 'Jania');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 197719, 'Johnette');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 879156, 'Claire');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 116081, 'Kristyn');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 402210, 'Lidia');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 381167, 'Hort');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 647738, 'Hobie');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 934782, 'Rice');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 729658, 'Wolf');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 283725, 'Corabella');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 632171, 'Concordia');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 449201, 'Lief');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 339880, 'Chrissie');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 586382, 'Griffin');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 601016, 'Raul');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 604845, 'Alyda');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 373790, 'Nadia');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 406162, 'Leann');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 668965, 'Julissa');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 408277, 'Emelia');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 668450, 'Viola');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 112519, 'Roch');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 487417, 'Liam');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 595222, 'Natale');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 513853, 'Blanche');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 481967, 'Mindy');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 862163, 'Nicolina');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 510818, 'Jameson');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 4690, 'Judi');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 408134, 'Kissie');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 656647, 'Teresa');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 789143, 'Daisi');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 151276, 'Eric');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 500207, 'Rozina');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 450230, 'Fanya');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 515628, 'Aubrey');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 976593, 'Shantee');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 666594, 'Reggy');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 469654, 'Cass');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 566469, 'Esdras');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 441161, 'Lynett');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 103675, 'Vyky');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 513914, 'Dick');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 748976, 'Vergil');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 687607, 'Erinna');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 294871, 'Tarah');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 827776, 'Selma');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 876655, 'Emelita');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 123832, 'Herve');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 394596, 'Taryn');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 561851, 'Cyndy');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 426239, 'Zane');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 888643, 'Elias');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 236210, 'Haze');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 651326, 'Anica');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 200888, 'Valentin');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 740406, 'Nevil');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 187047, 'Valry');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 675921, 'Elana');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 236242, 'Annabel');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 263474, 'Leela');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 382962, 'Panchito');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 417642, 'Agathe');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 914321, 'Ilise');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 329753, 'Julius');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 438377, 'Ailbert');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 218848, 'Penny');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 106260, 'Neale');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 534393, 'Traci');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 421376, 'Mohandas');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 610136, 'Price');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 580068, 'Carla');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 357465, 'Anatollo');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 951284, 'Aileen');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 694134, 'Sandro');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 503664, 'Sydelle');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 646228, 'Heda');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 374082, 'Brucie');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 6900, 'Adrianna');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 543916, 'Grenville');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 261274, 'Vladimir');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 551221, 'Caril');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 120522, 'Lorant');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 369634, 'Bennie');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 15824, 'Amie');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 492626, 'Calli');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 408195, 'Harbert');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 548022, 'Jess');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 991415, 'Kiele');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 266283, 'Essie');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 184769, 'Sharron');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 977932, 'Stanleigh');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 470277, 'Arlina');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 363452, 'Boyce');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 982923, 'Arnaldo');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 81337, 'Morty');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 4509, 'Steven');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 543433, 'Aylmer');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 314941, 'Estevan');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 511228, 'Trisha');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 562486, 'Bessy');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 747969, 'Collin');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 821313, 'Jermayne');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 532648, 'Thorvald');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 204840, 'Bertrando');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 672358, 'Monro');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 454971, 'Val');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 775331, 'Ranice');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 86209, 'Myles');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 652323, 'David');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 484105, 'Marven');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 70401, 'Alejandrina');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 255755, 'Dareen');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 311710, 'Jada');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 423246, 'Tandie');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 948833, 'Haze');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 947728, 'Brandtr');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 151572, 'Burt');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 434819, 'Kirbie');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 109439, 'Rafe');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 656276, 'Marie');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 950057, 'Frederica');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 716193, 'Daniela');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 624964, 'Korney');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 979432, 'Biddy');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 695719, 'Maxie');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 845238, 'Christian');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 292489, 'Hal');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 889826, 'Donielle');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 728594, 'Constantia');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 120070, 'Rosene');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 973179, 'Malissa');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 630217, 'Linet');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 713301, 'Eadie');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 804762, 'Idalia');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 262991, 'Hatti');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 134033, 'Aubree');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 808535, 'Jessee');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 975796, 'Onfroi');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 918714, 'Piotr');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 466709, 'Welby');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 561814, 'Toma');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 459247, 'Feodora');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 575390, 'Paula');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 952289, 'Karole');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 928093, 'Joella');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 477940, 'Stephan');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 761716, 'Iolanthe');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 768509, 'Berry');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 317499, 'Veronika');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 56604, 'Welbie');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 974466, 'Dorolisa');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 168584, 'Earvin');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 499745, 'Florian');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 46481, 'Velma');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order is ready', 715744, 'Ebba');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 412303, 'Glennie');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 320159, 'Ellyn');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 827933, 'Clint');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 712243, 'Bethanne');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 789073, 'Fredericka');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('start making your order', 556287, 'Jerry');
INSERT INTO Customer (sms_status_RestOrder, Customer_ID, Full_Name) VALUES ('order recive', 685147, 'Bernadine');
